// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"XERO_NoLoad","status":true,"description":"타이틀 화면 이어하기 버튼 제거","parameters":{}},
{"name":"XERO_TitleStyle","status":true,"description":"타이틀 커맨드창: LINESeedKR BD 폰트 / 흰색 / 22px / 커서 깜빡임 제거","parameters":{}},
{"name":"XERO_HUD","status":true,"description":"좌상단 HUD — 주인공 페이스 / 이름 / 심리 HP 바 (변수 1번)","parameters":{}}
];
