// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"XERO_NoLoad","status":true,"description":"Remove load/continue button.","parameters":{}},
{"name":"XERO_AudioExt","status":true,"description":"Loads selected custom audio files with their actual extensions.","parameters":{}},
{"name":"XERO_TitleStyle","status":true,"description":"Custom title command styling.","parameters":{}},
{"name":"XERO_HUD","status":true,"description":"Custom HUD.","parameters":{}},
{"name":"XERO_HpDamageNotice","status":true,"description":"Shows message when HP decreases.","parameters":{}},
{"name":"XERO_MessageAdvanceSe","status":true,"description":"Subtle message advance sound.","parameters":{}},
{"name":"XERO_MessageBookIcon","status":true,"description":"Draw book icon escape code in messages.","parameters":{}},
{"name":"XERO_ObjectiveHint","status":true,"description":"Blinking objective hints.","parameters":{}},
{"name":"XERO_MsgWhite","status":true,"description":"Force message text to white.","parameters":{}},
{"name":"XERO_MessageOpacity","status":true,"description":"Transparent message window background.","parameters":{}},
{"name":"XERO_MessageHeight","status":true,"description":"Slightly reduces the default message window height.","parameters":{"heightOffset":"24"}},
{"name":"XERO_BustPictureOffset","status":true,"description":"Raises, clears, and suppresses dialogue bust pictures.","parameters":{"yOffset":"36","bustPictureIds":"10,11","focusPictureNames":"selfie,phone"}},
{"name":"XERO_WASDMove","status":true,"description":"WASD movement.","parameters":{}},
{"name":"XERO_MapBoundaryGuard","status":true,"description":"Prevents walking onto map boundaries.","parameters":{}},
{"name":"XERO_LargeTilesetSupport","status":true,"description":"Render oversized custom tileset sheets without changing map data.","parameters":{}},
{"name":"XERO_DangerText","status":true,"description":"Danger text font and color.","parameters":{}},
{"name":"XERO_ChoiceColor","status":true,"description":"Choice text color.","parameters":{}},
{"name":"XERO_CharScale","status":true,"description":"Character sprite scale.","parameters":{"scale":"1.0"}}
];
